// This is the annotated source code for
// [wobot](https://github.com/cjoudrey/wobot), a plugin-based HipChat bot. See
// the [README](https://github.com/cjoudrey/wobot/blob/master/README.md) for
// information on installation and usage.
//
// This annotated source HTML is generated by
// [Docco](http://jashkenas.github.com/docco/).

// ## Table of contents

// The [Bot](bot.html) instances connect to HipChat and have a pluggable
// interface.
module.exports.Bot = require('./bot').Bot;
